"""Shared, named constants for the domain layer. No magic numbers elsewhere."""

from risk_orchestrator_agent.domain.constants.limits import (
    DEFAULT_RISK_SCORE_TTL_SECONDS,
    MAX_CORRELATION_STRENGTH,
    MAX_RISK_SCORE,
    MAX_UNIT_INTERVAL,
    MIN_CORRELATION_STRENGTH,
    MIN_DISTINCT_AGENTS_FOR_COMPOUND_FINDING,
    MIN_RISK_SCORE,
    MIN_UNIT_INTERVAL,
    PLATFORM_MIN_CONFIDENCE,
    PRIORITY_TIERS,
    SEVERITY_BANDS,
    TOTAL_PIPELINE_BUDGET_MS,
    UUID_STRING_LENGTH,
)

__all__ = [
    "DEFAULT_RISK_SCORE_TTL_SECONDS",
    "MAX_CORRELATION_STRENGTH",
    "MAX_RISK_SCORE",
    "MAX_UNIT_INTERVAL",
    "MIN_CORRELATION_STRENGTH",
    "MIN_DISTINCT_AGENTS_FOR_COMPOUND_FINDING",
    "MIN_RISK_SCORE",
    "MIN_UNIT_INTERVAL",
    "PLATFORM_MIN_CONFIDENCE",
    "PRIORITY_TIERS",
    "SEVERITY_BANDS",
    "TOTAL_PIPELINE_BUDGET_MS",
    "UUID_STRING_LENGTH",
]
