"""
============================================================
Sentinel Data Engine

Action Request Event

Official implementation of the ActionRequest
contract.
============================================================
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from uuid import uuid4


@dataclass
class ActionRequestEvent:

    # =====================================================
    # Event Header
    # =====================================================

    event_id: str = field(default_factory=lambda: str(uuid4()))

    event_type: str = "ActionRequest"

    event_version: int = 1

    event_timestamp: int = field(
        default_factory=lambda: int(
            datetime.now(
                timezone.utc
            ).timestamp() * 1000
        )
    )

    correlation_id: str = field(
        default_factory=lambda: str(uuid4())
    )

    causation_id: str | None = None

    producer_service: str = "ResponseAgent"

    producer_version: str = "1.0.0"

    site_id: str = ""

    zone_id: str | None = None

    partition_key: str = ""

    trace_id: str | None = None

    # =====================================================
    # Metadata
    # =====================================================

    metadata: dict = field(default_factory=dict)

    justification: dict = field(default_factory=dict)

    payload: dict = field(default_factory=dict)

    # =====================================================

    def set_action_request(

        self,

        action_id: str,

        risk_id: str,

        action_type: str,

        target_ref: str,

        requested_by: str,

        urgency: str,

        requires_human_approval: bool = True,

        requires_dual_control: bool = False,

        confidence: float = 0.95,

        summary: str = ""

    ):

        self.partition_key = target_ref

        self.justification = {

            "summary": summary,

            "confidence": {

                "value": confidence

            },

            "reasoning": [

                "Generated by Sentinel Response Agent"

            ]

        }

        self.payload = {

            "action_id": action_id,

            "risk_id": risk_id,

            "action_type": action_type,

            "target_ref": target_ref,

            "requested_by": requested_by,

            "urgency": urgency,

            "requires_human_approval": requires_human_approval,

            "requires_dual_control": requires_dual_control

        }

    # =====================================================

    def to_dict(self):

        return {

            "event_id": self.event_id,

            "event_type": self.event_type,

            "event_version": self.event_version,

            "event_timestamp": self.event_timestamp,

            "correlation_id": self.correlation_id,

            "causation_id": self.causation_id,

            "producer_service": self.producer_service,

            "producer_version": self.producer_version,

            "site_id": self.site_id,

            "zone_id": self.zone_id,

            "partition_key": self.partition_key,

            "trace_id": self.trace_id,

            "metadata": self.metadata,

            "justification": self.justification,

            "payload": self.payload

        }